### ISSUE TITLE
The extension doesn't appear to do anything in my browser

### ISSUE THREAD

**Issue by tobius** [Krxtopher/github-style-stash#1]
I am testing with my Todo project and see no different rendering result from a source view, markdown view, or browse view. Are there further setup instructions or have I found a Chrome edge case?

**Comment by Krxtopher** [comment]
@tobius, try making sure you access the site through the stash.resource.com domain. The extension is hard coded to only effect that domain. If you are using the local domain(?) shortcut of "http://stash" it won't work. Let me know the result you get.

**Comment by lukeaskew** [comment]
I had the same issue when accessing via http://git.resource.com.

Using stash.resource.com resolved the issue.

**Comment by tobius** [comment]
I misunderstood the project intention and was testing Github flavored markdown support (I crave Markdown tables in Stash). Your styles are all working properly, nice work Kris.
